### ISSUE TITLE
P5.3 integration: 'NoneType' object has no attribute 'foo'

### ISSUE THREAD

**Issue by tildebyte** [jdf/processing.py#161]
Where `foo` is an attribute of an external Python class which is part of the sketch.
Example:
In **Topics/Simulate/ForcesWithVectors**: Line 32, calling `liquid.display()`

````java
processing.app.SketchException: AttributeError: 'NoneType' object has no attribute 'display'
at jycessing.mode.run.SketchRunner.convertPythonSketchError(Unknown Source)
at jycessing.mode.run.SketchRunner.access$300(Unknown Source)
at jycessing.mode.run.SketchRunner$3.run(Unknown Source)
at java.lang.Thread.run(Thread.java:745)
````

**Comment by tildebyte** [comment]
I'll add more sketches if/when I come across them.

**Comment by jdf** [comment]
Please paste into this bug some sort of repro case.

**Comment by jdf** [comment]
That's just a missing "global".

**Comment by tildebyte** [comment]
Derp. Too long away.
