### ISSUE TITLE
P5.3 integration: "size() cannot be used here"

### ISSUE THREAD

**Issue by tildebyte** [jdf/processing.py#162]
First ran into this in **Basics/Color/ColorVariables**, but the minimal test case is e.g. `size(640, 360)` as the *only* line in a sketch. The Java equivalent works as expected.

````java
processing.app.SketchException: java.lang.IllegalStateException: size() cannot be used here, see https://processing.org/reference/size_.html
	at processing.core.PApplet.insideSettings(PApplet.java:933)
	at processing.core.PApplet.size(PApplet.java:1965)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:496)
	at org.python.core.PyObject.__call__(PyObject.java:500)
	at org.python.core.PyMethod.__call__(PyMethod.java:156)
	at org.python.pycode._pyx21.f$0(ColorVariables.pyde:7)
	at org.python.pycode._pyx21.call_function(ColorVariables.pyde)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.Py.exec(Py.java:1430)
	at org.python.pycode._pyx20.f$0(/var/folders/ql/9rtt57rj3y36wwmfpn80fyn80000gn/T/ColorVariables2346867237380832299/ColorVariables.pyde:84)
	at org.python.pycode._pyx20.call_function(/var/folders/ql/9rtt57rj3y36wwmfpn80fyn80000gn/T/ColorVariables2346867237380832299/ColorVariables.pyde)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.Py.exec(Py.java:1430)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:276)
	at jycessing.PAppletJythonDriver.processSketch(PAppletJythonDriver.java:176)
	at jycessing.PAppletJythonDriver.setup(PAppletJythonDriver.java:945)
	at processing.core.PApplet.handleDraw(PApplet.java:2374)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1527)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:229)
	at jycessing.mode.run.SketchRunner.access$4(SketchRunner.java:226)
	at jycessing.mode.run.SketchRunner$3.run(SketchRunner.java:121)
	at java.lang.Thread.run(Thread.java:745)
````

**Comment by GoToLoop** [comment]
https://Processing.org/reference/settings_.html

**Comment by kazimuth** [comment]
I would guess that P5.3 parses the sketch to find the size() call, pulls it out of wherever it's called, and puts it in settings(). Unless it's called with variable arguments, in which case it complains unless it's in settings(){ ... }.

That's a possibility here as well - you can check out [ImportExtractor.java](https://github.com/jdf/processing.py/blob/master/runtime/src/jycessing/mode/export/ImportExtractor.java), which calls into Jython's ANTLR python parser.

**Comment by GoToLoop** [comment]
Not only **size()** is transported into **settings()**, but also **smooth()**.
Although I wonder why **size()** w/ variables are not allowed, since they don't mind its 3rd argument.

**Comment by tildebyte** [comment]
1) Clearly I was unclear. The *exact* code tested was `size(640, 360)`. I intended for `size(x, y)` to indicate that the actual values didn't matter. 

2) The P5 docs for `size()` indicate that `size()` can be the first (or for that matter only) line of a sketch.

**Comment by GoToLoop** [comment]
> The P5 docs for **size()** indicate that **size()** can be the first...

That's only true for Java Mode's pre-processor! Other modes need to implement their own!

**Comment by kazimuth** [comment]
Also **fullScreen()**, probably.

And size's third argument is still a "constant", P2D or P3D, which the preprocessor probably knows about.

**Comment by GoToLoop** [comment]
>> ... which the preprocessor probably knows about.

Still I fail to see why the pre-processor couldn't simply copy & paste the whole **size()** statement into **settings()**!  :P

**Comment by kazimuth** [comment]
```java
void settings() {}

void setup() {
    int x = 100;
    size(x, x);
}
```

**Comment by tildebyte** [comment]
@kazimuth What are you trying to say? That's not runnable in Java mode...
@anyone Is there any documentation showing how the *Python* mode works? P5.3 docs say "The settings() function is... not needed in most sketches. It's only useful when it's absolutely necessary to define the parameters to size() with a variable." Should P5.py behave the same?

**Comment by GoToLoop** [comment]
Indeed that'd be hard to pull off! I wasn't thinking about variables but rather constant fields like:  

```processing
static final W = 800, H = 600;

void setup() {
  size(W, H, FX2D);
  smooth(4);
}
```

**Comment by tildebyte** [comment]
Updated the initial report for clarity (hopefully).

**Comment by GoToLoop** [comment]
>> Should P5.py behave the same?

As said, that behavior is exclusive to Java Mode. Other modes need to choose whether they wish to follow suit.

**Comment by kazimuth** [comment]
@GoToLoop yeah, that's valid. Figuring out that it's valid is hard, though, and requires more semantic information than is easily accessible in the AST.
@tildebyte just explaining why simply transplanting a call to size() to settings(){} won't always work.

I would say that there's no real reason it shouldn't behave the same way. The underlying machinery must rely on size() being called in settings(), so we need to make sure that it is eventually called there; the current way it works in Java Mode seems like a reasonable compromise.

**Comment by tildebyte** [comment]
This changes existing behavior for P5.py (see **Basics/Color/ColorVariables**, as I mentioned). Any sketch which is not defined inside of a function(s) won't work because `size()` will now be required to live inside of one (e.g. usually `setup()`).
Not my circus; I actually prefer having more structured code, but it should at least be documented.

**Comment by GoToLoop** [comment]
>> Figuring out that it's valid is hard, ...

IMO, they shouldn't try to figure that out. Just transplant 1st **setup()** & **smooth()** into **settings()** w/o any modifications if there's no explicit **settings()**.
After all, If pre-processor fails to do that, compile's gonna fail either way.
At least if those arguments happen to be fields rather than local variables, the copy'n'paste approach's gonna work.

**Comment by kazimuth** [comment]
It should be possible to fix that with preprocessing, but there will have to be some large changes.

**Comment by jdf** [comment]
Deployed as build 3003.

**Comment by Assaelero** [comment]
hi, sorry to comment in this closed issue and sorry about my english, i have solved your problem, i just download a old version and shazam all done. best regards
