### ISSUE TITLE
Cannot run Python examples with `java.security.ProtectionDomain`

### ISSUE THREAD

**Issue by Spaxe** [jdf/processing.py#208]
Reproduce with Build 3017 in Examples/Demos/Graphics/Particles.

Some others may or may not work properly.

I don't know how to deal with this stacktrace as I've never seen it before. @jdf?

Full stacktrace:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at processing.app.SketchCode.getDocumentText(SketchCode.java:228)
	at processing.app.ui.Editor.prepareRun(Editor.java:2716)
	at jycessing.mode.PyEditor.runSketch(PyEditor.java:300)
	at jycessing.mode.PyEditor.handleRun(PyEditor.java:343)
	at jycessing.mode.PyToolbar.handleRun(PyToolbar.java:22)
	at processing.app.ui.EditorToolbar$1.actionPerformed(EditorToolbar.java:158)
	at processing.app.ui.EditorButton.mousePressed(EditorButton.java:181)
	at java.awt.Component.processMouseEvent(Component.java:6530)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4522)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by jdf** [comment]
Reproduced.

**Comment by DominusDodo** [comment]
Found this problem today. It's fixed when you cycle through all tabs; presumably they are not loaded until they are clicked on, resulting in the empty document object.

**Comment by DominusDodo** [comment]
This doesn't occur (I think) if not other tabs are open other than the primary one, so the additional tabs are the issue.

```java
  private void loadSavedCode() {
    SketchCode[] code = sketch.getCode();
    for (int i=0; i<code.length; i++) {
      if (!code[i].getProgram().equals(code[i].getSavedProgram())) {
        code[i].setProgram(code[i].getSavedProgram());
        /* Wild Hack: set document to null so the text editor will refresh
           the program contents when the document tab is being clicked */
        code[i].setDocument(null);
      }
    }
    // this will update the current code
    setCode(sketch.getCurrentCode());
  }
```

Here the document for each tab is set to null. `JavaEditor#setCode` called its super class' `Editor#setCode`, which contains:

```java
SyntaxDocument document = (SyntaxDocument) code.getDocument();
...
code.setDocument(document);
```

So the primary tab (the initially selected one) is loaded but not the other opened tabs. This loads the tabs when clicked, but keeps them unfortunately unloaded until then. A fix might be to run `setCode(sketch.getCurrentCode());` on all tabs, and then again on the primary tab outside the for loop:

```java
  private void loadSavedCode() {
    SketchCode[] code = sketch.getCode();
    for (int i=0; i<code.length; i++) {
      if (!code[i].getProgram().equals(code[i].getSavedProgram())) {
        code[i].setProgram(code[i].getSavedProgram());
        /* Don't set document to null because this results in unloaded tabs if
           they have not been viewed before running; instead set the code
           documents, loading them all at the start, and then set the primary tab below
        setCode(code[i]);
      }
    }
    // this will update the current code
    setCode(sketch.getCurrentCode());
  }
```

If this interferes with tab updating, another fix may be required.

**Comment by DominusDodo** [comment]
The fix is even simpler than this. Catching the NullPointerException in Editor#prepareRun seems to fix it with no side effects. I've submitted a fix and pull request to the main Processing branch.

**Comment by Spaxe** [comment]
Confirmed that clicking through every tab fixes this issue. Thanks all.

**Comment by jdf** [comment]
Thanks for your research. I don't believe the patch you've proposed is a good one, because it papers over an error without addressing its cause. I'll address this as soon as I've got a free moment.

**Comment by DominusDodo** [comment]
Do you mean the patch described above (agreed, bad) or the patch in the pull request linked above, which catches an anticipated NullPointerException caused by setting document to null elsewhere as part of the document reloading?
