### ISSUE TITLE
External Python libraries installed with Pip won't import

### ISSUE THREAD

**Issue by LoganDark** [jdf/processing.py#232]
I have PIL installed for python 2.7, 3.5 and 3.6, and it won't import. I'm using the latest version of Processing.py.

Java error:
```
processing.app.SketchException: ImportError: No module named PIL
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:248)
	at jycessing.mode.run.SketchRunner.access$4(SketchRunner.java:227)
	at jycessing.mode.run.SketchRunner$3.run(SketchRunner.java:122)
	at java.lang.Thread.run(Thread.java:745)
```

Faulty line:
```
import PIL
```

**Comment by LoganDark** [comment]
Come to think of it, you can't import *any* Python-specific libraries from Processing.py.

**Comment by jdf** [comment]
Python Mode does not use the system Python, and is not compatible with any Python libraries that use native components (those with native code dynamic libraries).

**Comment by LoganDark** [comment]
Oh. Sux
