### ISSUE TITLE
problem working with processing in non-English locale

### ISSUE THREAD

**Issue by zoe-L** [jdf/processing.py#253]
Hi! 
While I'm trying to run scripts in processing.py, I encounter the following error:
`Exception in thread "main" java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
	at org.python.core.PyString.<init>(PyString.java:64)
	at org.python.core.PyString.<init>(PyString.java:70)
	at org.python.core.Py.newString(Py.java:641)
	at org.python.core.PySystemState.initRegistry(PySystemState.java:800)
	at org.python.core.PySystemState.doInitialize(PySystemState.java:1045)
	at org.python.core.PySystemState.initialize(PySystemState.java:974)
	at org.python.core.PySystemState.initialize(PySystemState.java:930)
	at org.python.core.PySystemState.initialize(PySystemState.java:925)
	at org.python.util.jython.run(jython.java:263)
	at org.python.util.jython.main(jython.java:142)
`

After a quick search, I found that this error is similar to the following in jython:
http://bugs.jython.org/issue2331
https://github.com/jythontools/jython/commit/c61eaefb774cdb174472265d3c27fc5b87febd34

Any help will be appreciated!

**Comment by jdf** [comment]
I don't see any of the processing.py code in that stack trace. How are you invoking the program?

**Comment by zoe-L** [comment]
Sorry I'm not being clear about this. This error message displays right after I started Processing in python mode, and is causing any subsequent attempt to run any code to fail. But I don't seem to have any problem when running Processing in Java (no error message etc.).

**Comment by jdf** [comment]
What is your operating system, and what is your user name on your computer?

**Comment by zoe-L** [comment]
I'm using windows 10 and my username is something not ascii. ("石榴李") So I suspect that is causing the problem.

**Comment by jdf** [comment]
Thank you. There's some problem associated with non-ASCII user names that I haven't yet tracked down. It's my top priority to find and fix it. Meanwhile, you can work around it by creating a second login just for working in Python Mode, with an ASCII user name. I'm very sorry for the inconvenience.

**Comment by jdf** [comment]
I should have said, non-ASCII user names _on a Windows machine_.

**Comment by jdf** [comment]
So I've created a user 大山 (not quite "Feinberg"; more like "Grossberg") on a Windows 10 machine, and I can't get even close to testing Python Mode because *nothing* works. I can't run Eclipse. I can't run Processing at all. Everything just crashes because not a single piece of software expects non-ascii characters in the file path. I'll keep trying to find a way to test it, but I'm losing hope. How do you even run processing?

**Comment by zoe-L** [comment]
Thank you so much for the replies! I've created another account and was able to get around the problem. Also, regarding running processing itself under non-ascii user name, I would have to say I have no idea on that. I haven't tried to run any code in the java mode, but all I can say about that is that the console does not display error message immediately after I open the program. So it might not be a problem that specific to  prosessing.py.
