### ISSUE TITLE
PDF Export not working.

### ISSUE THREAD

**Issue by Enteleform** [jdf/processing.py#270]
```
System:
    Windows 10
    Processing.py 3025
```
&nbsp;  

```
Exception: This sketch requires the "pdf" library. at 8:0 in OneFrame.py
```

**Comment by villares** [comment]
Hi @Enteleform! From the same tutorial, have you seen this part:

> The Processing IDE has a helpful "Add Library" feature that allows you to locate, download and use these libraries in your project using a GUI interface. Of course, on the command line, that option isn't available to you! So here's what you do:
> 
>     Make a subdirectory called 'libraries' in the same directory as your sketch file.
>     Download the Processing library that you want to use. Depending on the library, it can sometimes be tricky to find the right file to download. The Processing Wiki has good advice on how to identify the appropriate file and how to find the relevant files within that repository
>     Extract the library's archive file (usually a ZIP file) and copy the resulting directory into the libraries subdirectory that you just created.
> 
> If you're having trouble locating the right file to download for a particular library, there's a helpful alternative technique. Use the Processing IDE's "Add Library" feature to download and install the library for use in the IDE.

**Comment by Enteleform** [comment]
@villares 
I'm familiar with the process to install 3rd party libraries, however; the `PDF` library appears to be a core `Processing` library, and is included with the `Processing.py` distribution @ `processing.py-3017-windows64\libraries\processing\pdf`.

**Comment by jdf** [comment]
Hi. PDF export is working fine in Python Mode. I haven't attended to the command-line processing-py build for a long time, and I regret that it's broken.

Meanwhile, please provide a complete, minimal example that reproduces the error.

**Comment by Enteleform** [comment]
@jdf 

`processing.py-3017-windows64\examples.py\Library\PDF Export\OneFrame.py`  
from
`processing.py-windows64.zip`
is the file referenced in the first post:

```python
"""
 * One Frame.
 *
 * Saves one PDF with the contents of the display window.
 * Because this example uses beginRecord, the image is shown
 * on the display window and is saved to the file.
"""

#from processing.pdf import *

size(600, 600)

beginRecord(PDF, "line.pdf")

background(255)
stroke(0, 20)
strokeWeight(20.0)
line(200, 0, 400, height)

endRecord()
```

**Comment by jdf** [comment]
The one line that would make it work, if it were going to work, is commented out (the import).

**Comment by Enteleform** [comment]
@jdf

The commented line throws an exception, as do the alternatives:

&nbsp;  

`from processing.pdf import *`
```
import * does not work in this environment. at 8:0 in OneFrame.py
```

&nbsp;  

`add_library("pdf")`
```
Exception: This sketch requires the "pdf" library. at 9:0 in OneFrame.py
```

&nbsp;  

`add_library("processing.pdf")`
```
Exception: This sketch requires the "processing.pdf" library. at 10:0 in OneFrame.py
```

**Comment by jdf** [comment]
Instead of using the string `"PDF"`, try `"processing.pdf.PGraphicsPDF"`.

**Comment by Enteleform** [comment]
@jdf 

&nbsp;

`add_library("processing.pdf.PGraphicsPDF")`

```python
Exception: This sketch requires the "processing.pdf.PGraphicsPDF" library. at 10:0 in OneFrame.py
```

&nbsp;

`from processing.pdf.PGraphicsPDF import PDF`
works, but results in the same exception as detailed in the first post.&nbsp; It seems that the issue isn't making `PDF` accessible; since it already is by default, along with other injected objects/functions like `size`, `colorMode` `background` `rect`, etc.
```
java.lang.RuntimeException: The processing.pdf.PGraphicsPDF renderer is not in the class path.
	at processing.core.PApplet.makeGraphics(PApplet.java:2259)
	at processing.core.PApplet.createGraphics(PApplet.java:2170)
	at processing.core.PApplet.beginRecord(PApplet.java:10503)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
	at org.python.core.PyObject.__call__(PyObject.java:496)
	at org.python.core.PyObject.__call__(PyObject.java:500)
	at org.python.core.PyMethod.__call__(PyMethod.java:156)
	at org.python.pycode._pyx4.f$0(OneFrame.py:20)
	at org.python.pycode._pyx4.call_function(OneFrame.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.core.Py.exec(Py.java:1430)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:276)
	at jycessing.PAppletJythonDriver.setup(PAppletJythonDriver.java:1038)
	at processing.core.PApplet.handleDraw(PApplet.java:2378)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1527)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)
```

**Comment by jdf** [comment]
```python
size(600, 600)

beginRecord("processing.pdf.PGraphicsPDF", "line.pdf")

background(255)
stroke(0, 20)
strokeWeight(20.0)
line(200, 0, 400, height)

endRecord()
```

**Comment by Enteleform** [comment]
@jdf 

Just tried it & it throws the same exception.

**Comment by GanerCodes** [comment]
bump

**Comment by baltner** [comment]
I don't even have a PDF library in my environment, as shown in the attached image, which is looking at the untarred distribution for macosx. Is this why I keep getting the message that the processing.pdf.PGraphicsPDF renderer is not in the class path?
<img width="346" alt="Screen Shot 2022-11-14 at 1 48 31 PM" src="https://user-images.githubusercontent.com/753683/201742637-a1cab35d-a621-49ae-9364-56805fbe64b3.png">
