### ISSUE TITLE
New Release breaks PeasyCam - arg can't be coerced to processing.core.PApplet, processing.core.PGraphics

### ISSUE THREAD

**Issue by Ocupe** [jdf/processing.py#297]
Hello, I guess with the last release a bug snuck in. The below code was working before the last update and know fails.

The here provided sketch thoughts an exception on the second last line with this error: ```processing.app.SketchException: TypeError: apply(): 1st arg can't be coerced to processing.core.PApplet, processing.core.PGraphics
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:240)
	at jycessing.mode.run.SketchRunner.lambda$2(SketchRunner.java:119)
	at java.lang.Thread.run(Thread.java:748)```
```
add_library('peasycam')
from peasy import PeasyCam

def setup():
    size(500, 500, P2D)
    global cam 
    cam = PeasyCam(this, 400)
    global canvas
    canvas = createGraphics(width, height, P3D)
    
def draw():
    canvas.beginDraw()
    canvas.background(55);
    canvas.pushMatrix();
    canvas.fill(150, 255, 255);
    canvas.sphere(60);
    canvas.popMatrix();
    canvas.endDraw();
    
    cam.getState().apply(canvas)
    image(canvas, 0, 0)
```
Thank you for the great work :)

**Comment by Ocupe** [comment]
Don't be sorry for that. Thank you very much for the super fast fix! 👍
