### ISSUE TITLE
loadImage method doesn't work when used in settings method at the command line

### ISSUE THREAD

**Issue by berinhard** [jdf/processing.py#325]
I'm using the `processing-py.sh` script to run my sketches and I ran into an issue with it when trying to use `loadImage` method in the `settings` function. It's raising Java's `NullPointerException` for no reason. The tricky thing is that the very **same code** that breaks with the command line, works when being executed using the Python mode inside the Processing IDE.

I've wrote 2 sketches to reproduce the error and both of them do the same thing, they only differ on when they are reading the image and how they are calling the `size` method. The first one reads the image in the `setup` method and passes hardcoded values to the `size` method, while the second one, which reproduces the bug, reads it in the `setting` method and uses the image dimensions. You can take a look at them [here](https://github.com/berinhard/sketches/tree/master/s_034).

Java's complete traceback is here:

```
java.lang.NullPointerException
    at processing.core.PApplet.loadImage(PApplet.java:5250)
    at processing.core.PApplet.loadImage(PApplet.java:5225)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:186)
    at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:204)
    at org.python.core.PyObject.__call__(PyObject.java:478)
    at org.python.core.PyObject.__call__(PyObject.java:482)
    at org.python.core.PyMethod.__call__(PyMethod.java:141)
    at org.python.pycode._pyx5.settings$1(s_034_settings.pyde:14)
    at org.python.pycode._pyx5.call_function(s_034_settings.pyde)
    at org.python.core.PyTableCode.call(PyTableCode.java:167)
    at org.python.core.PyBaseCode.call(PyBaseCode.java:124)
    at org.python.core.PyFunction.__call__(PyFunction.java:403)
    at org.python.core.PyFunction.__call__(PyFunction.java:398)
    at jycessing.PAppletJythonDriver.settings(PAppletJythonDriver.java:1005)
    at processing.core.PApplet.handleSettings(PApplet.java:962)
    at processing.core.PApplet.runSketch(PApplet.java:10264)
    at jycessing.PAppletJythonDriver.runAndBlock(PAppletJythonDriver.java:644)
    at jycessing.Runner.runSketchBlocking(Runner.java:395)
    at jycessing.Runner.runSketchBlocking(Runner.java:282)
    at jycessing.Runner.main(Runner.java:182)
```

**Comment by berinhard** [comment]
PS.: I'm a Python developer too. So, if you can point me which direction/how I can investigate this issue, I'll be happy to help.

**Comment by jdf** [comment]
https://processing.org/reference/settings_.html

> The settings() method runs before the sketch has been set up, so other Processing functions cannot be used at that point. For instance, do not use loadImage() inside settings().
