### ISSUE TITLE
PVector.fromAngle does not return a Python Mode-compatible PVector

### ISSUE THREAD

**Issue by berinhard** [jdf/processing.py#334]
The example `ParticleSystemPShape` is raising an error. It's located under `Topics > Create Shapes`. 

The exception I'm being raised at the line 61 and its description is:

```
processing.app.SketchException: TypeError: 'processing.core.PVector' object is unsubscriptable
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:240)
	at jycessing.mode.run.SketchRunner.lambda$2(SketchRunner.java:119)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by jdf** [comment]
Pushed in version 3050.
