### ISSUE TITLE
Exception in thread "main" java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by zamqiness** [jdf/processing.py#349]
Hello there,  I want to learn Processing in Python, but sadly the installation was a failure in both of my computers (one is brand-new). I downloaded x64 version, unzipped at desktop, installed python mode from the top right button then got this error: 

Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.python.core.PyType.init(PyType.java:633)
	at org.python.core.PyType.createType(PyType.java:1523)
	at org.python.core.PyType.addFromClass(PyType.java:1462)
	at org.python.core.PyType.fromClass(PyType.java:1551)
	at org.python.core.PyType.fromClass(PyType.java:1536)
	at org.python.core.PyStringMap.getLazyType(PyStringMap.java:68)
	at org.python.core.PyStringMap.<init>(PyStringMap.java:48)
	at org.python.core.PyStringMap.<init>(PyStringMap.java:44)
	at org.python.expose.BaseTypeBuilder.getDict(BaseTypeBuilder.java:49)
	at org.python.core.PyType.init(PyType.java:621)
	at org.python.core.PyType.addBuilder(PyType.java:1452)
	at org.python.core.PyType.<clinit>(PyType.java)
	at org.python.core.PyObject.<init>(PyObject.java:93)
	at org.python.core.PyBuiltinCallable.<init>(PyBuiltinCallable.java:22)
	at org.python.core.PyBuiltinMethod.<init>(PyBuiltinMethod.java:16)
	at org.python.core.PyBuiltinMethodNarrow.<init>(PyBuiltinMethodNarrow.java:23)
	at org.python.core.PyDataDescr$getset_descriptor___get___exposer.<init>(Unknown Source)
	at org.python.core.PyDataDescr$PyExposer.<init>(Unknown Source)
	at org.python.core.PyDataDescr.<clinit>(PyDataDescr.java)
	at org.python.core.PyBuiltinCallable$PyExposer.<init>(Unknown Source)
	at org.python.core.PyBuiltinCallable.<clinit>(PyBuiltinCallable.java)
	at org.python.core.PyObject$PyExposer.<init>(Unknown Source)
	at org.python.core.PyObject.<clinit>(PyObject.java)
	at org.python.util.jython.run(jython.java:241)
	at org.python.util.jython.main(jython.java:142)
Caused by: java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
	at org.python.core.PyString.<init>(PyString.java:57)
	at org.python.core.PyString.<init>(PyString.java:70)
	at org.python.core.PyString.<init>(PyString.java:74)
	at org.python.core.Py.newString(Py.java:647)
	at org.python.core.PyJavaType.init(PyJavaType.java:585)
	at org.python.core.PyType.createType(PyType.java:1523)
	at org.python.core.PyType.addFromClass(PyType.java:1462)
	at org.python.core.PyType.fromClass(PyType.java:1551)
	at org.python.core.PyObject.<init>(PyObject.java:93)
	at org.python.core.PySingleton.<init>(PySingleton.java:9)
	at org.python.core.PyNotImplemented.<init>(PyNotImplemented.java:10)
	at org.python.core.Py.<clinit>(Py.java:94)
	... 25 more

When I run a code, I start to see a slider at the bottom right side but that's it. I also tried Java version and works perfectly fine. People told online that it can happen if pc username has non-English characters but no, mine don't have that. Thanks for your help! :p

**Comment by jdf** [comment]
Hi. Does this happen with a new, completely empty sketch?

**Comment by zamqiness** [comment]
The error happens before than anything, slider thing shows up only after I put up a code (i put ellipse(50,50,80,80) in my last trial). Have firewall disabled, and also I tried on another computer(this is third) same error, though all of them were tried on the same IP.
