### ISSUE TITLE
Starter example not working

### ISSUE THREAD

**Issue by pikeas** [jdf/processing.py#357]
The example at https://github.com/jdf/processing.py/blob/master/workspace/example.py is broken, in both IDE and standalone modes.

In IDE or standalone:

```
processing.app.SketchException: NameError: global name 'displayWidth' is not defined
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:242)
	at jycessing.mode.run.SketchRunner.lambda$2(SketchRunner.java:119)
	at java.lang.Thread.run(Thread.java:748)
```
Alright, let's replace `displayWidth` and `displayHeight` with fixed dimensions.

In IDE (Processing 3.5.3):

```
processing.app.SketchException: AttributeError: 'NoneType' object has no attribute 'setTitle'
	at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:242)
	at jycessing.mode.run.SketchRunner.lambda$2(SketchRunner.java:119)
	at java.lang.Thread.run(Thread.java:748)
```

In standalone (https://py.processing.org/tutorials/command-line/):

```
java.lang.UnsatisfiedLinkError: Can't load library: <sketch path>/natives/macosx-universal//gluegen-rt
```

I'm more interested in the standalone mode but ideally this "hello world" sketch would work in either mode. This is a bad new user experience.

**Comment by villares** [comment]
Hi @pikeas,

I'm not sure what these examples you found are (maybe some internal development). 
The true end user examples are kept here: https://github.com/jdf/processing.py/tree/master/examples.py and under File>Examples... in the IDE

**Comment by jeremydouglass** [comment]
@villares -- it looks like that /workplace/example.py is the default script used by processing-py.bat and processing-py.sh

https://github.com/jdf/processing.py/search?q=example.py&unscoped_q=example.py

It is also seven years old. It might need to be updated or removed, but I haven't looked at how the command line launchers currently use it -- I've never attempted to have run them with a default sketch before (I didn't even realize this was possible).
