### ISSUE TITLE
3D Image Example Explode.py not working

### ISSUE THREAD

**Issue by sandeepcoder097** [jdf/processing.py#358]
The example at (https://github.com/jdf/processing.py/blob/master/examples.py/3D/Image/Explode.py) is not working in IDE.
In IDE (Processing 3.5.4):
_AttributeError: 'NoneType' object has no attribute 'width'_
>processing.app.SketchException: AttributeError: 'NoneType' object has no attribute 'width'
>at jycessing.mode.run.SketchRunner.convertPythonSketchError(SketchRunner.java:242)
>at jycessing.mode.run.SketchRunner.lambda$2(SketchRunner.java:119)
>at java.lang.Thread.run(Thread.java:748)

**Comment by FeXd** [comment]
You not having the required image `eames.jpg` in your `data` folder. When you run `img = loadImage("eames.jpg")  # Load the image` it is failing to find the image, so `img` is now `NoneType`.

You will see that there is a `data` folder with the [required image file](https://github.com/jdf/processing.py/blob/master/examples.py/3D/Image/data/eames.jpg) if you look at the example's root directory: [https://github.com/jdf/processing.py/tree/master/examples.py/3D/Image](https://github.com/jdf/processing.py/tree/master/examples.py/3D/Image)

Your folder structure should look like this: 
![image](https://user-images.githubusercontent.com/553767/75817143-23f73780-5d5c-11ea-8149-014872db43f2.png)
