### ISSUE TITLE
Python mode update | Error message

### ISSUE THREAD

**Issue by spprocessing** [jdf/processing.py#370]
Hi everyone,

Today (03/05/2020) I installed a new update for python mode in Processing, and, after that, I am having the following error message in the console every time I try to run the sketch.
I believe the problem is present because I am using in my sketch two libraries (Sound and PeasyCam), but before the update installation everything was just fine. Is this just a bug in the new update for Python mode? Am I supposed to do something different in this new update importing those libraries? I'll be very grateful If anyone can help me with this issue.

Error Message:

NullPointerException
at java.util.Objects.requireNonNull(Objects.java:203)
at java.util.Arrays$ArrayList.(Arrays.java:3813)
at java.util.Arrays.asList(Arrays.java:3800)
at jycessing.LibraryImporter.findResources(Unknown Source)
at jycessing.LibraryImporter.recursivelyLoadNativeLibraryies(Unknown Source)
at jycessing.LibraryImporter.addLibrary(Unknown Source)
at jycessing.LibraryImporter$1.call(Unknown Source)
at org.python.core.PyObject.call(PyObject.java:480)
at org.python.core.PyObject.call(PyObject.java:484)
at org.python.pycode._pyx11.f$0(spherical_phase_space.pyde:1)
at org.python.pycode._pyx11.call_function(spherical_phase_space.pyde)
at org.python.core.PyTableCode.call(PyTableCode.java:171)
at org.python.core.PyCode.call(PyCode.java:18)
at org.python.core.Py.runCode(Py.java:1614)
at org.python.core.Py.exec(Py.java:1658)
at org.python.pycode._pyx10.f$0(C:/Users/Samuel/OneDrive/TESE/spherical_phase_space/spherical_phase_space.pyde:96)
at org.python.pycode._pyx10.call_function(C:/Users/Samuel/OneDrive/TESE/spherical_phase_space/spherical_phase_space.pyde)
at org.python.core.PyTableCode.call(PyTableCode.java:171)
at org.python.core.PyCode.call(PyCode.java:18)
at org.python.core.Py.runCode(Py.java:1614)
at org.python.core.Py.exec(Py.java:1658)
at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:276)
at jycessing.PAppletJythonDriver.processSketch(Unknown Source)
at jycessing.PAppletJythonDriver.findSketchMethods(Unknown Source)
at jycessing.Runner.runSketchBlocking(Unknown Source)
at jycessing.mode.run.SketchRunner.lambda$startSketch$3(Unknown Source)
at java.lang.Thread.run(Thread.java:748)

**Comment by mpsftw** [comment]
Have you been able to get this working? I recognize that error from a bug I fixed a while back.

**Comment by spprocessing** [comment]
Hi,

Yes! The error was solved one or two months ago. 

Thanks
