### ISSUE TITLE
Generated Application on MacOS fails to Launch

### ISSUE THREAD

**Issue by seanmpuckett** [jdf/processing.py#371]
With the current 3059 release, applications exported on MacOS 10.14.6 show the processing.py splash but go no further.  Applications exported on 3056 on the same platform work as expected.

**Comment by mpsftw** [comment]
I've been unable to replicate this on 3062. Can you update and try it again?

**Comment by seanmpuckett** [comment]
Issue persists on 3062. 

Extra information: adding the controlP5 library seems to trigger the issue; a trivial test script will generate a functional app; however adding the line

add_library('controlP5')

to the trivial script -- without any other modifications -- causes the generated app to fail to launch. ControlP5 version is the current one in the tools library: 2.2.6.  Note this was not a failure issue in processing.py 3056.

The only console log information I've recovered is an XPC failure with an exit code of 255, probably not indicative.

**Comment by mpsftw** [comment]
Ok. I've been able to replicate it with this:

```
add_library('ControlP5')

def setup():
    size(10,10)
```

It works fine as a PDESketch.

Error:
```
sketch_371.pyde:1: RuntimeWarning: PyTableCode.call caught a Throwable that is not an Exception:
java.lang.NoClassDefFoundError: processing/app/Platform
Jython internals might be in a bad state now that can cause deadlocks later on.
See http://bugs.jython.org/issue2536 for details.
  add_library('ControlP5')
java.lang.ClassNotFoundException: processing.app.Platform
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at jycessing.LibraryImporter.addLibrary(LibraryImporter.java:142)
	at jycessing.LibraryImporter$1.__call__(LibraryImporter.java:83)
	at org.python.core.PyObject.__call__(PyObject.java:480)
	at org.python.core.PyObject.__call__(PyObject.java:484)
	at org.python.pycode._pyx5.f$0(sketch_371.pyde:1)
	at org.python.pycode._pyx5.call_function(sketch_371.pyde)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.Py.exec(Py.java:1658)
	at org.python.pycode._pyx4.f$0(/Users/molly/Development/Processing.org/processing.py_bugs/sketch_371/application.macosx/sketch_371.app/Contents/Processing/source/sketch_371.pyde:96)
	at org.python.pycode._pyx4.call_function(/Users/molly/Development/Processing.org/processing.py_bugs/sketch_371/application.macosx/sketch_371.app/Contents/Processing/source/sketch_371.pyde)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.Py.exec(Py.java:1658)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:276)
	at jycessing.PAppletJythonDriver.processSketch(PAppletJythonDriver.java:230)
	at jycessing.PAppletJythonDriver.findSketchMethods(PAppletJythonDriver.java:590)
	at jycessing.Runner.runSketchBlocking(Runner.java:399)
	at jycessing.Runner.runSketchBlocking(Runner.java:280)
	at jycessing.Runner.main(Runner.java:185)
```

I'll take a look at it.

**Comment by mpsftw** [comment]
3063 should work for you.

**Comment by seanmpuckett** [comment]
Confirmed, this now works with my application. Thank you!
