### ISSUE TITLE
Reference to `frame` in `PApplet` should be removed?

### ISSUE THREAD

**Issue by benfry** [jdf/processing.py#382]
Getting a `NoSuchFieldError` on startup with Python Mode with 4.0 alpha 2 because `frame` has been removed, and it seems like there's some sort of workaround that sets it `null` on startup:

https://github.com/jdf/processing.py/blob/master/runtime/src/jycessing/PAppletJythonDriver.java#L460

If this is still necessary, perhaps reflection to avoid calling this with newer `PApplet`?

**Comment by jdf** [comment]
Thanks, Ben; will move to reflection ASAP.

**Comment by tabreturn** [comment]
Should Python Mode work in the 4.0a3 release? I've just tested it, but it won't work on my computer (Linux).

**Comment by tabreturn** [comment]
Should Python Mode work in the 4.0a3 release? I've just tested it, but it won't run a sketch on my computer (Linux).

**Comment by villares** [comment]
> Should Python Mode work in the 4.0a3 release? I've just tested it, but it won't run a sketch on my computer (Linux).

Alpha 4 today, but I suppose there needs to me a mode update removing the `frame` reference before it works...

**Comment by benfry** [comment]
A possible PR to get this process rolling, I know @jdf is busy, so perhaps others could help with testing it further: https://github.com/jdf/processing.py/pull/389

**Comment by tabreturn** [comment]
I build and test this, then let you know how it goes.

**Comment by tabreturn** [comment]
Nope! Can't manage to build it (using Linux). I did this a while back ... I'm not sure how now.

I'm sure I used these instructions:
https://github.com/jdf/processing.py/blob/master/HOWTO-HACK.txt

When I run `ant test`, I get:
```
...
jre-download:
[downloader] Downloading /home/nuc/Desktop/processing-source/processing.py/linux/jre-8u202.tgz from https://download.processing.org/java/jre-8u202-linux-i586.tar.gz

BUILD FAILED
/home/nuc/Desktop/processing-source/processing.py/build.xml:216: The following error occurred while executing this line:
/home/nuc/Desktop/processing-source/processing/build/build.xml:310: The following error occurred while executing this line:
/home/nuc/Desktop/processing-source/processing/build/build.xml:255: java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createTempFile(File.java:2061)
	at Downloader.download(Downloader.java:158)
	at Downloader.execute(Downloader.java:91)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:106)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:36)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:437)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
	at org.apache.tools.ant.Main.runBuild(Main.java:830)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
```

I think I might have fixed this somehow last time. Any hints?

**Comment by tabreturn** [comment]
So far so good. Will keep testing.

If anybody needs a build, here you go: https://github.com/tabreturn/processing.py-for-processing-4

**Comment by tabreturn** [comment]
First issue to note --

I get a `WARNING: An illegal reflective access operation has occurred` every other time I open Processing. So, I just need to close and restart if this happens.

Linux Mint 20.1 (Ubuntu Focal based)

Full console output:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by jnr.posix.JavaLibCHelper (file:/home/nuc/.sketchbook/modes/PythonMode/mode/jython.jar) to method sun.nio.ch.SelChImpl.getFD()
WARNING: Please consider reporting this to the maintainers of jnr.posix.JavaLibCHelper
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by villares** [comment]
I think it is working for most things, but I think I'm crashing doing `Save As...` from the menu.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by processing.app.platform.LinuxPlatform (file:/home/villares/other-software/processing-4.0a4/lib/pde.jar) to field sun.awt.X11.XToolkit.awtAppClassName
WARNING: Please consider reporting this to the maintainers of processing.app.platform.LinuxPlatform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
created registry at port 8220
/home/villares/sketchbook/modes/PythonMode/formatter/pep8.py:100: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
could not create registry; assume it's already created
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.core.PyJavaType (file:/home/villares/sketchbook/modes/PythonMode/mode/jython.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.python.core.PyJavaType
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f2e05e5812c, pid=51710, tid=51854
#
# JRE version: OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (11.0.11+9) (build 11.0.11+9)
# Java VM: OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (11.0.11+9, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  0x00007f2e05e5812c
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %h" (or dumping to /home/villares/other-software/processing-4.0a4/core.51710)
#
# An error report file with more information is saved as:
# /home/villares/other-software/processing-4.0a4/hs_err_pid51710.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```
[hs_err_pid51710.log](https://github.com/jdf/processing.py/files/6677300/hs_err_pid51710.log)

**Comment by benfry** [comment]
One of the “illegal reflective access” issues I've logged here: https://github.com/processing/processing4/issues/207

Though most of those look like they're inside Jython. Would probably be a good idea to update to the latest Jython in case any of those are resolved. (Java 9+ is more fussy about making methods `public` or otherwise accessible via reflection, which Jython may do a lot of.)

**Comment by benfry** [comment]
The fatal error, however is trickier—the Save As shouldn't be hitting any native code from Processing (which is required for that type of crash) so there may be a bad interaction between the Java VM and your Window Manager.

**Comment by jdf** [comment]
Hi, folks. It's very hard for me to find time for this--the project really does need a new owner--but I will try to update to a more recent Jython. It's difficult to do because I have to patch the implementation to make the behavior of large integer constants less surprising.

**Comment by villares** [comment]
Hi,

Testing @tabreturn's mode build on Processing 4a6 on Windows I've got this:

![image](https://user-images.githubusercontent.com/3694604/128104067-7f16842e-f4d2-48f7-9b68-07bfea481263.png)

**Comment by benfry** [comment]
@villares Ok, just pushed a fix for that one to the Processing 4 source (that code was making the assumption that all Modes would have an `ErrorTable`, which is not correct). For other issues, you'll probably want to open something separate, since this issue is just about `frame` in `PApplet`.

**Comment by tabreturn** [comment]
Thanks, @benfry. I built Processing 4 from the latest source; Python mode is running again :snake::+1:

**Comment by benfry** [comment]
Oh, and the “Save As” crash may be resolved by the solution described here: https://github.com/processing/processing4/issues/233#issuecomment-892615250
