### ISSUE TITLE
"first sketch" program not display on processing 4.0

### ISSUE THREAD

**Issue by seb16120** [jdf/processing.py#396]
Hi,
Nothing append when i run that code :

```py
def setup():
    size(600, 600)
    colorMode(HSB)
    noStroke()


def draw():
    fill(0x11000000)
    rect(0, 0, width, height)
    fill(frameCount % 255, 255, 255)
    ellipse(mouseX, mouseY, 20, 20)
```

**Comment by seb16120** [comment]
i forget to call the 2 function so i called them and i get bug :

java.lang.NullPointerException
	at processing.core.PApplet.colorMode(PApplet.java:14872)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:188)
	at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:206)
	at org.python.core.PyObject.__call__(PyObject.java:497)
	at org.python.core.PyObject.__call__(PyObject.java:501)
	at org.python.core.PyMethod.__call__(PyMethod.java:141)
	at org.python.pycode._pyx11.setup$1(python_mode_test.pyde:7)
	at org.python.pycode._pyx11.call_function(python_mode_test.pyde)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:125)
	at org.python.core.PyFunction.__call__(PyFunction.java:403)
	at org.python.pycode._pyx11.f$0(python_mode_test.pyde:1)
	at org.python.pycode._pyx11.call_function(python_mode_test.pyde)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.Py.exec(Py.java:1658)
	at org.python.pycode._pyx10.f$0(C:\Users\gokus\AppData\Local\Temp\python_mode_test7356475793809306453\python_mode_test.pyde:96)
	at org.python.pycode._pyx10.call_function(C:\Users\gokus\AppData\Local\Temp\python_mode_test7356475793809306453\python_mode_test.pyde)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.Py.exec(Py.java:1658)
	at org.python.util.PythonInterpreter.exec(PythonInterpreter.java:276)
	at jycessing.PAppletJythonDriver.processSketch(Unknown Source)
	at jycessing.PAppletJythonDriver.findSketchMethods(Unknown Source)
	at jycessing.Runner.runSketchBlocking(Unknown Source)
	at jycessing.mode.run.SketchRunner.lambda$startSketch$3(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by tabreturn** [comment]
Use Processing 3.5.4 for Python Mode.

**Comment by seb16120** [comment]
ok, i will try
