### ISSUE TITLE
Window is not closed

### ISSUE THREAD

**Issue by Lythenas** [jdf/processing.py#419]
When the program stops/quits the window is not automatically closed. All animation etc. stops but the window remains open.

This happens in any way I tried. Just clicking "Run" means you now have two windows open. Clicking "Stop" will not close the window. And calling `exit` in code (or even `sys.exit`) does the same. In all cases the program will stop running but the window will stay open.

When running processing through the terminal it shows the following error:

```
Exception in thread "processing.py mode runner" java.lang.NoClassDefFoundError: processing/javafx/PSurfaceFX
	at jycessing.PAppletJythonDriver.runAndBlock(PAppletJythonDriver.java:952)
	at jycessing.Runner.runSketchBlocking(Runner.java:409)
	at jycessing.mode.run.SketchRunner.lambda$2(SketchRunner.java:112)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: processing.javafx.PSurfaceFX
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 4 more
```

Processing v4.3
Python Mode v4001

**Comment by tabreturn** [comment]
Use Processing 3.5.4 for Python Mode

**Comment by Lythenas** [comment]
Yes, that works. I also saw the readme mention that the python mode is based on processing 3.

But in processing 4 I was still able to install "Python Mode for Processing 4", which produced the above error. So this should still be fixed.

I'm not seeing much recent activity on this repo, so I'm going to leave this issue open. But feel free to close it if you prefer.
