### ISSUE TITLE
Python Processing Sketch Using Non-Default Renderer Does Not Load in IDE (on Linux)

### ISSUE THREAD

**Issue by Zishan-Rahman** [jdf/processing.py#420]
I discovered this after trying to address this issue that was opened in the Processing Flatpak's repository: flathub/org.processing.processingide#5. Specifically, I'd like to quote [a comment I posted there](https://github.com/flathub/org.processing.processingide/issues/5#issuecomment-1739983316) that describes the problem I, and another user @zWhdmB5T in the aforementioned issue's discussion, have. Note that the problem we're having isn't caused by Flatpak's sandbox and/or limitations. As I eventually determined, it exists even when running Processing outside of Flatpak. I use Linux Mint 21.2, while @zWhdmB5T uses openSUSE Leap 15.5.

> ...the problems I have with running Python sketches are specifically coming from those that use the optional `renderer` parameter in the `save(w, h, renderer)` method. [The processing.py documentation](https://py.processing.org/reference/size.html) explains what that parameter is used for, but in a nutshell, it's basically used in the `size` function to tell processing.py which renderer to use for a particular sketch in the `setup()` method of a `.pyde` file (the main file for a Python Processing sketch). The Koch ["Topics — Fractals and L-Systems — Koch"] and Mandelbrot ["Topics — Fractals and L-Systems — Mandelbrot"] sketches do not use this parameter when calling `size`, hence they use the default renderer, and that works fine. Where the issue arises, at least from _my_ observation, is when that optional parameter is used. The Particles ["Demos — Graphics — Particles"] sketch uses `P2D` for `renderer` when calling `size`, whereas the BoxClock example (found in "Demos — Graphics — BoxClock") uses `P3D`. On my computer, neither of them run. I tried running Processing 4.3 with Python mode outside of Flatpak's sandbox and the exact same problems occur. So after looking into it, I _can_ conclude that the problem we're both facing is likely on Python mode's end, and it's not a Flatpak-specific problem.

[I gave a comprehensive rundown of error messages I get when running Python mode in this comment](https://github.com/flathub/org.processing.processingide/issues/5#issuecomment-1738000565), but here are the two errors that are relevant to **this** specific problem.

Trying to run an example sketch (i.e. Particles or BoxClock) that uses `P2D` or `P3D` the first time:
```
java.lang.UnsatisfiedLinkError: Can't load library: /app/share/processing/natives/linux-amd64/libgluegen_rt.so
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:625)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:64)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:107)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:488)
	at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:427)
	at com.jogamp.common.os.Platform$1.run(Platform.java:321)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.jogamp.common.os.Platform.<clinit>(Platform.java:290)
	at com.jogamp.nativewindow.NativeWindowFactory$1.run(NativeWindowFactory.java:239)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.jogamp.nativewindow.NativeWindowFactory.<clinit>(NativeWindowFactory.java:236)
	at com.jogamp.newt.NewtFactory$1.run(NewtFactory.java:69)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.jogamp.newt.NewtFactory.<clinit>(NewtFactory.java:66)
	at processing.opengl.PSurfaceJOGL.initIcons(PSurfaceJOGL.java:492)
	at processing.opengl.PSurfaceJOGL.initFrame(PSurfaceJOGL.java:146)
	at processing.core.PApplet.initSurface(PApplet.java:10215)
	at jycessing.PAppletJythonDriver.initSurface(PAppletJythonDriver.java:472)
	at processing.core.PApplet.runSketch(PApplet.java:10121)
	at jycessing.PAppletJythonDriver.runAndBlock(PAppletJythonDriver.java:909)
	at jycessing.Runner.runSketchBlocking(Runner.java:409)
	at jycessing.mode.run.SketchRunner.lambda$2(SketchRunner.java:112)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Trying to run that example sketch the second time:
```
java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.newt.NewtFactory
	at processing.opengl.PSurfaceJOGL.initIcons(PSurfaceJOGL.java:492)
	at processing.opengl.PSurfaceJOGL.initFrame(PSurfaceJOGL.java:146)
	at processing.core.PApplet.initSurface(PApplet.java:10215)
	at jycessing.PAppletJythonDriver.initSurface(PAppletJythonDriver.java:472)
	at processing.core.PApplet.runSketch(PApplet.java:10121)
	at jycessing.PAppletJythonDriver.runAndBlock(PAppletJythonDriver.java:909)
	at jycessing.Runner.runSketchBlocking(Runner.java:409)
	at jycessing.mode.run.SketchRunner.lambda$2(SketchRunner.java:112)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.UnsatisfiedLinkError: Can't load library: /app/share/processing/natives/linux-amd64/libgluegen_rt.so [in thread "processing.py mode runner"]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2398)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:625)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:64)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:107)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:488)
	at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:427)
	at com.jogamp.common.os.Platform$1.run(Platform.java:321)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.jogamp.common.os.Platform.<clinit>(Platform.java:290)
	at com.jogamp.nativewindow.NativeWindowFactory$1.run(NativeWindowFactory.java:239)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.jogamp.nativewindow.NativeWindowFactory.<clinit>(NativeWindowFactory.java:236)
	at com.jogamp.newt.NewtFactory$1.run(NewtFactory.java:69)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.jogamp.newt.NewtFactory.<clinit>(NewtFactory.java:66)
	... 9 more
```

**Comment by tabreturn** [comment]
Use Processing 3.5.4 for Python Mode. For renderer issues, you might try this fix: https://github.com/processing/processing/issues/6061
